---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freva-web
  namespace: freva
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: incommon-cert-tds
      hosts:
        - www.freva-delopyment.cloud.dkrz.de
  rules:
    - host: www.freva-delopyment.cloud.dkrz.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-reverse-proxy
                port: {number: 80}
